import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Header from '@/components/header'
import "./globals.css";
import Footer from '@/components/footer'


const kanit = Kanit({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Humana services",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true} className={kanit.className}>

            <Header />
            <main className="">
              {children}
            </main>
            <Footer />

      </body>
    </html>
  );
}
